baseURL      = "https://cdcmi.com/"
theme        = "PaperMod"
canonifyURLs = true

# ── Song ngữ / Multilingual ──
defaultContentLanguage         = "vi"
defaultContentLanguageInSubdir = false

# ── Params chung (dùng cho mọi ngôn ngữ) ──
[params]
  ShowBreadCrumbs  = true
  ShowReadingTime  = true
  ShowPostNavLinks = true

  [params.cover]
    linkFullImages = true

  [params.assets]
    css = ["css/extended/custom.css"]

[params.author]
  name = "Công đoàn CMI"

# ── Cấu hình từng ngôn ngữ ──
[languages]

  [languages.vi]
    languageCode = "vi"
    languageName = "Tiếng Việt"
    weight       = 1
    title        = "Công đoàn CMI"

    [languages.vi.params.label]
      text       = "CÔNG TY TNHH CORSAIR MARINE INTERNATIONAL"
      icon       = "CMI_LOGO.jpeg"
      iconHeight = 50

  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight       = 2
    title        = "CMI Union"

    [languages.en.params.label]
      text       = "CORSAIR MARINE INTERNATIONAL CO., LTD."
      icon       = "CMI_LOGO.jpeg"
      iconHeight = 50

# ── Taxonomies ──
[taxonomies]
  tag      = "tags"
  category = "categories"
  archives = "archives"

# ── Markup ──
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
